services:
  # Servisimizin adı (istediğiniz bir şey olabilir)
  redis-server:
    image: redis:7-alpine
    container_name: my-redis
    # --- AOF (Kalıcılık) için En Önemli Kısım ---
    # Konteyner başladığında çalıştırılacak komut.
    # redis-server'ı --appendonly yes bayrağıyla çalıştırarak AOF modunu zorluyoruz.
    # --save 60 1: Her 60 saniyede, en az 1 anahtar değiştiyse RDB snapshot alınır.
    # --requirepass: Redis'e bağlanmak için şifre zorunlu kılınır.
    command: redis-server --save 60 1 --appendonly yes --requirepass "Password12*"
    ports:
    - 6379:6379
    volumes:
      # --- Verilerin Kalıcılığı için En Önemli Kısım ---
      # 'redis-data' adında bir "named volume" oluşturuyoruz.
      # Bu volume, Redis'in veri dizini olan '/data' klasörüne bağlanıyor.
      # AOF dosyası (appendonly.aof) bu klasörde saklanır.
      # 'docker-compose down' yapsanız bile bu volume silinmez.
      - redis-data:/data

# Docker'a 'redis-data' adında bir volume yönetmesini söylüyoruz.
volumes:
  redis-data: